#%RAML 0.8
title: microrest.php Example API
version: v1
baseUrl: http://localhost:8888/api
mediaType: application/json
/posts:
  displayName: Posts
  get:
    description: Retrieves one or more posts.
    responses:
      200:
  post:
    description: Creates one or more posts.
    responses:
      201:
  /{id}:
    get:
      description: Retrieves one or more posts.
      responses:
        200:
    put:
      description: Updates one or more posts.
      responses:
        204:
    delete:
      description: Deletes one or more posts.
/tags:
  displayName: Tags
  get:
    description: Retrieves one or more tags.
    responses:
      200:
  post:
    description: Creates one or more tags.
    responses:
      201:
  /{id}:
    get:
      description: Retrieves one or more tags.
      responses:
        200:
    put:
      description: Updates one or more tags.
      responses:
        204:
    delete:
      description: Deletes one or more tags.
/comments:
  displayName: Comments
  get:
    description: Retrieves one or more comments.
    responses:
      200:
  post:
    description: Creates one or more comments.
    responses:
      201:
  /{id}:
    get:
      description: Retrieves one or more comments.
      responses:
        200:
    put:
      description: Updates one or more comments.
      responses:
        204:
    delete:
      description: Deletes one or more comments.
